[workspace]
members = ["benches/", "crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["DaniPopes <57450786+DaniPopes@users.noreply.github.com>"]
edition = "2021"
rust-version = "1.77"
license = "MIT OR Apache-2.0"
categories = ["compilers", "cryptography::cryptocurrencies"]
keywords = ["compile", "compiler", "jit", "evm", "ethereum"]
homepage = "https://github.com/danipopes/cranelift-jit-evm"
repository = "https://github.com/danipopes/cranelift-jit-evm"
exclude = [".github/", "benches/", "fuzz/", "tests/"]

[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = "deny"
rustdoc.all = "warn"

[workspace.dependencies]
revm-jit = { version = "0.1.0", path = "crates/revm-jit", default-features = false }
revm-jit-backend = { version = "0.1.0", path = "crates/revm-jit-backend", default-features = false }
revm-jit-builtins = { version = "0.1.0", path = "crates/revm-jit-builtins", default-features = false }
revm-jit-context = { version = "0.1.0", path = "crates/revm-jit-context", default-features = false }
revm-jit-cranelift = { version = "0.1.0", path = "crates/revm-jit-cranelift", default-features = false }
revm-jit-llvm = { version = "0.1.0", path = "crates/revm-jit-llvm", default-features = false }

alloy-primitives = { version = "0.7.0", default-features = false }
revm-primitives = { version = "3.1.1", default-features = false }
revm-interpreter = { version = "4.0.0", default-features = false }
ruint = { version = "1.12.1", default-features = false }

color-eyre = "0.6"
eyre = "0.6"
rustc-hash = "1.1"
tracing = "0.1"
tracing-error = "0.2"
tracing-subscriber = "0.3"

[patch.crates-io]
# revm-primitives = { git = "https://github.com/bluealloy/revm", rev = "cfc4511fe148296394c19c9ab3fb46f663218413" }
# revm-interpreter = { git = "https://github.com/bluealloy/revm", rev = "cfc4511fe148296394c19c9ab3fb46f663218413" }
revm-primitives = { git = "https://github.com/danipopes/revm", branch = "refactor-opinfo" }
revm-interpreter = { git = "https://github.com/danipopes/revm", branch = "refactor-opinfo" }
